-- Create locations table
CREATE TABLE public.locations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  country TEXT NOT NULL DEFAULT 'SG',
  region TEXT,
  is_24h BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Locations are viewable by authenticated users"
  ON public.locations FOR SELECT
  TO authenticated
  USING (true);

-- Create visits table
CREATE TABLE public.visits (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  location_id UUID NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, location_id)
);

ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own visits"
  ON public.visits FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own visits"
  ON public.visits FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own visits"
  ON public.visits FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- Create profiles table
CREATE TABLE public.profiles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile"
  ON public.profiles FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own profile"
  ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own profile"
  ON public.profiles FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (user_id)
  VALUES (NEW.id);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Indexes
CREATE INDEX idx_visits_user_id ON public.visits(user_id);
CREATE INDEX idx_visits_location_id ON public.visits(location_id);
CREATE INDEX idx_locations_country ON public.locations(country);-- Allow everyone (including anonymous visitors) to read the locations table.
-- The app shows an interactive map as the public home page, so we need read
-- access without authentication. Visits remain user-scoped.

DROP POLICY IF EXISTS "Locations are viewable by authenticated users" ON public.locations;

CREATE POLICY "Locations are viewable by everyone"
  ON public.locations FOR SELECT
  TO anon, authenticated
  USING (true);
-- Seed all Anytime Fitness Singapore outlets.
-- Generated by scripts/generate-seed.mjs
-- Source: https://www.anytimefitness.sg/locations/sg/<region>/ (2026-04-19)

DELETE FROM public.locations WHERE country = 'SG';

INSERT INTO public.locations (name, address, lat, lng, country, region, is_24h) VALUES
  ('Ang Mo Kio', 'Broadway Plaza, 4190 Ang Mo Kio Avenue 6 #01-02', 1.3762884, 103.8448366, 'SG', 'Central', true),
  ('Anytime Fitness Balmoral', '32 Stevens Road #02-01 @Novotel Stevens, Singapore 258892', 1.314059, 103.8276982, 'SG', 'Central', true),
  ('Balestier', '288 Balestier Road', 1.3231868, 103.8526929, 'SG', 'Central', true),
  ('Bedok 200 North Avenue', '200 Bedok North Ave 1, Singapore 469752', 1.3274509, 103.9273194, 'SG', 'Central', true),
  ('Bedok Central', '445 Bedok North Street 1 #03-01 Djitsun Mall Bedok', 1.3260725, 103.9295131, 'SG', 'Central', true),
  ('Bishan', 'Blk 505, Bishan Street 11 #01-438', 1.3488904, 103.8487153, 'SG', 'Central', true),
  ('Bishan 227', '227, Bishan Street 23, #B1-79, Singapore 570227', 1.3580922, 103.8471298, 'SG', 'Central', true),
  ('Boon Keng', '294A/B Lavender Street Singapore 338807', 1.3123505, 103.8614704, 'SG', 'Central', true),
  ('Buangkok', 'Hougang Green Shopping Mall, 21 Hougang Street 51 #02-13A', 1.3788331, 103.8876981, 'SG', 'Central', true),
  ('Bugis', '51 Middle Road #03-01 & #04-01 Singapore 188959', 1.2972901, 103.8552318, 'SG', 'Central', true),
  ('Bukit Merah Central', '161 Bukit Merah Central Singapore 150161', 1.2840845, 103.8159939, 'SG', 'Central', true),
  ('Bukit Panjang CC', 'Unit #03-01, Bukit Panjang Community Club, 8 Pending Road', 1.376001, 103.770687, 'SG', 'Central', true),
  ('Bukit Timah', 'Bukit Timah Shopping Centre #B1-01, 170 Upper Bukit Timah Road', 1.3431064, 103.7762382, 'SG', 'Central', true),
  ('Bukit Timah Central', '559 Bukit Timah Rd, #B1-01 King’s Arcade', 1.3233285, 103.8108037, 'SG', 'Central', true),
  ('Cineleisure Orchard', '8 Grange Road, Singapore 239695', 1.301527, 103.8363441, 'SG', 'Central', true),
  ('Clarke Quay', '3A River Valley Rd, #02-05 Clarke Quay, Singapore 179020', 1.2903646, 103.8448929, 'SG', 'Central', true),
  ('Dakota', '87 Jalan Satu #02-01', 1.3096771, 103.887485, 'SG', 'Central', true),
  ('Dhoby Ghaut', '1 Selegie Road, #03-02, Singapore 188306', 1.3001382, 103.8490685, 'SG', 'Central', true),
  ('Dunearn', '896 Dunearn Road, #01-23 Dunearn Village, Singapore', 1.336791, 103.7836817, 'SG', 'Central', true),
  ('Eastwood Centre', 'Eastwood Centre, 20 Eastwood Rd, Singapore 486442', 1.3215353, 103.9555422, 'SG', 'Central', true),
  ('Henderson CC', '500 Bukit Merah View, Singapore 159682', 1.2859171, 103.823354, 'SG', 'Central', true),
  ('HillV2', '4 Hillview Rise #02-18/19 HillV2', 1.3630144, 103.7641958, 'SG', 'Central', true),
  ('Holland Village', '31A Lorong Mambong', 1.3116106, 103.7943913, 'SG', 'Central', true),
  ('Hougang 915', '915 Hougang Street 91, #01-10, Singapore 530915', 1.3775517, 103.8837018, 'SG', 'Central', true),
  ('Hougang Central', '1187 Upper Serangoon Road #B1-01 The Midtown', 1.3704086, 103.8951078, 'SG', 'Central', true),
  ('Jalan Besar', 'Rehau Building, 1 King George''s Avenue #01-00', 1.3071291, 103.8586211, 'SG', 'Central', true),
  ('Kallang', '4 Jalan Ayer, Singapore 389142', 1.3110999, 103.8729082, 'SG', 'Central', true),
  ('Kebun Baru CC', '216 Ang Mo Kio Ave. 4, #02-04 Kebun Baru CC', 1.3730072, 103.837616, 'SG', 'Central', true),
  ('Keppel', '1557 Keppel Rd, #01-03', 1.2722598, 103.834388, 'SG', 'Central', true),
  ('Kim Seng Community Centre', '570 Havelock Rd', 1.2895666, 103.8307713, 'SG', 'Central', true),
  ('Lentor Modern', '1 Lentor Central #B1-01/02 Lentor Modern Singapore 788887', 1.3862963, 103.8337522, 'SG', 'Central', true),
  ('MacPherson Mall', '401 MacPherson Rd, Singapore 368125', 1.3316968, 103.8794435, 'SG', 'Central', true),
  ('New Queensway', '1 Queensway #03-51, Queensway Shopping Centre, Singapore 149053', 1.2875231, 103.8031063, 'SG', 'Central', true),
  ('New Upper Thomson', '246S Upper Thomson Road', 1.3535126, 103.8346162, 'SG', 'Central', true),
  ('Nex', '23 Serangoon Central, #04-73/74/75 Nex,', 1.350745, 103.872736, 'SG', 'Central', true),
  ('Novena', '101 Thomson Road #B1-15/16/17/34 United Square,', 1.3171474, 103.8435716, 'SG', 'Central', true),
  ('Orchard', '277 Orchard Rd, #04-01 Orchardgateway', 1.3002793, 103.8388322, 'SG', 'Central', true),
  ('Potong Pasir', 'No. 15 Tai Thong Crescent', 1.329348, 103.8694793, 'SG', 'Central', true),
  ('Rochester', '41 Rochester Drive, Singapore 138582', 1.3059921, 103.7876779, 'SG', 'Central', true),
  ('Serangoon Gardens', '53 Serangoon Garden Way', 1.3632228, 103.8664862, 'SG', 'Central', true),
  ('Simpang Bedok', '430 Upper Changi Road, Singapore 487048', 1.3318464, 103.9463496, 'SG', 'Central', true),
  ('Still Road', '155 Still Rd, Boon Court', 1.3153951, 103.905519, 'SG', 'Central', true),
  ('Suntec City', '3 Temasek Boulevard, Suntec City, Singapore 038983', 1.2950324, 103.8583015, 'SG', 'Central', true),
  ('Tampines 487', '487B Tampines Street 45 #B1-123, Singapore 521487', 1.359985, 103.958264, 'SG', 'Central', true),
  ('Tampines North', '492B Tampines Avenue 9 #01-422, S(520492)', 1.3630113, 103.9534981, 'SG', 'Central', true),
  ('Tanjong Pagar', '10 Anson Road, International Plaza, #03-41', 1.2760013, 103.8459347, 'SG', 'Central', true),
  ('Tekka Place', '2 Serangoon Road #02-17 to #02-21 Tekka Place Singapore 218227', 1.3050631, 103.8514261, 'SG', 'Central', true),
  ('The Burghley', '45 Burghley Drive Singapore 559022', 1.3595239, 103.8595889, 'SG', 'Central', true),
  ('The Concourse', 'The Concourse 300 Beach Road #02-01A/02 Singapore 199555', 1.3010505, 103.8626595, 'SG', 'Central', true),
  ('Thomson CC', '194 Upper Thomson Rd, #02-01, Singapore 574339', 1.3512279, 103.836323, 'SG', 'Central', true),
  ('Toa Payoh', 'Blk 190 Lorong 6 Toa Payoh #03-512', 1.3329648, 103.8486276, 'SG', 'Central', true),
  ('Upper Serangoon', '780 Upper Serangoon Rd, Singapore 534626', 1.3541786, 103.878809, 'SG', 'Central', true),
  ('VIIO @ BALESTIER', '520 Balestier Rd, #03-01 to 04', 1.3270809, 103.8459447, 'SG', 'Central', true),
  ('Valley Point', 'Valley Point Shopping Centre 491 River Valley Road, #02-02', 1.2933441, 103.8271408, 'SG', 'Central', true),
  ('Wave 9', 'Wave 9, 71 Woodlands Industrial Park E9, Singapore 757048', 1.448648, 103.7975372, 'SG', 'Central', true),
  ('Wheelock Place', '501 Orchard Road #05-13/14', 1.3047411, 103.8305926, 'SG', 'Central', true),
  ('Woodlands 11', '11 Woodlands Cl, #01-02, Singapore 737853', 1.4343653, 103.8024411, 'SG', 'Central', true),
  ('Admiralty', '31 Woodlands Avenue 6, #05-01/02 Woodlands Galaxy Community Club', 1.4390853, 103.8026836, 'SG', 'North East', true),
  ('Ang Mo Kio 548', '548 Ang Mo Kio Ave 10, Singapore 560548', 1.3728759, 103.8570791, 'SG', 'North East', true),
  ('Bedok 510', '510 Bedok North Street 3, Singapore 460510', 1.3323592, 103.9305587, 'SG', 'North East', true),
  ('Bukit Batok (Le Quest)', '4 Bukit Batok St 41 #01-96/99/100', 1.3557202, 103.7408471, 'SG', 'North East', true),
  ('Changi City Point', '#02-02C 5 Changi Business Park Central 1, Singapore 486038', 1.3343497, 103.9626223, 'SG', 'North East', true),
  ('Chong Pang', '369 Sembawang Road, #01-03', 1.426939, 103.8261113, 'SG', 'North East', true),
  ('City Hall', '1 Raffles Link #B1-47 CityLink Mall', 1.292053, 103.8558562, 'SG', 'North East', true),
  ('Clementi 354', 'Blk 354, Clementi Ave 2, #01-183, Singapore 120354', 1.3135272, 103.7708724, 'SG', 'North East', true),
  ('Elias CC', '93 Pasir Ris Drive 3 #01-05 Pasir Ris Elias Community Centre', 1.3783171, 103.942769, 'SG', 'North East', true),
  ('Gambas', 'Nordcom II, 2 Gambas Cres, Singapore 757044', 1.4432352, 103.8160436, 'SG', 'North East', true),
  ('Greenwich', '1 Seletar Road #02-05/06 Greenwich V Singapore', 1.3873705, 103.8694069, 'SG', 'North East', true),
  ('Hougang CC', 'Hougang Community Club, 35 Hougang Ave 3', 1.3646889, 103.8924308, 'SG', 'North East', true),
  ('Hwi Yoh', '23 Serangoon North Ave 4, #01-01', 1.3755232, 103.8734244, 'SG', 'North East', true),
  ('Junction 9', 'Junction 9 Shopping Mall, 18 Yishun Avenue 9,#02-32/33', 1.433148, 103.8417427, 'SG', 'North East', true),
  ('Khoo Teck Puat Hospital', '01-02 Yishun Community Hospital (YCH) 2 Yishun Central 2 Singapore 768024', 1.4237956, 103.8371525, 'SG', 'North East', true),
  ('Kovan', 'JForte Sportainment Centre Level 2 50 Hougang Ave 1, Singapore 538885', 1.3604143, 103.8880508, 'SG', 'North East', true),
  ('Loyang Point', '258 Pasir Ris Street 21, #05-03/04/05 Loyang Point', 1.3663238, 103.9640002, 'SG', 'North East', true),
  ('Marsiling CC', '100 Admirality Road', 1.4406497, 103.7736396, 'SG', 'North East', true),
  ('New Tech Park', '151 Lorong Chuan #01-12', 1.3526598, 103.8598608, 'SG', 'North East', true),
  ('Northpoint City', '1 Northpoint Drive, #02-175-178 South Wing of Northpoint City', 1.4284725, 103.8359864, 'SG', 'North East', true),
  ('Northshore Plaza', '407 Northshore Drive, #01-20 to 25, Northshore Plaza I', 1.4147604, 103.8998921, 'SG', 'North East', true),
  ('Pasir Ris E!Hub', 'E!Hub @ Downtown East, 1 Pasir Ris Close, #05-105', 1.3777334, 103.9546444, 'SG', 'North East', true),
  ('Punggol Oasis', '681 Punggol Drive, Oasis Terraces, #01-16', 1.4026301, 103.9129247, 'SG', 'North East', true),
  ('Punggol Waterway', '654A Punggol Dr., Waterway Sunrise 2, Singapore 821654', 1.3971142, 103.9205688, 'SG', 'North East', true),
  ('SKH Campus', 'Sengkang Community Hospital, 1 Anchorvale Street #01-29', 1.3963094, 103.8911356, 'SG', 'North East', true),
  ('Sengkang Rivervale', '11 Rivervale Crescent, Rivervale Mall, #02-01', 1.3922624, 103.9044463, 'SG', 'North East', true),
  ('Tampines', '#03-361 Block 506 Tampines Central 1,', 1.3559399, 103.9458359, 'SG', 'North East', true),
  ('Tampines Central', '866A Tampines Street 83, #03-10, Tampines Central Community Complex', 1.3553724, 103.9344296, 'SG', 'North East', true),
  ('Tampines North', 'Blk 492B Tampines Avenue 9 #01-422, Singapore 520492', 1.3630113, 103.9534981, 'SG', 'North East', true),
  ('Tampines West', '5 Tampines Avenue 3, #02-03, Tampines West Community Club', 1.3494959, 103.9343031, 'SG', 'North East', true),
  ('Upper Changi', 'Unit #02-12/13/14 Komo Shoppes 963C Upper Changi Rd N. Singapore 506790', 1.3603618, 103.9701466, 'SG', 'North East', true),
  ('Woods Square', 'No 8 Woodlands Square #02-12/13/14/15/16, SOLO 2', 1.4359958, 103.7874069, 'SG', 'North East', true),
  ('Yishun East', '461 Yishun Ave 6, Singapore 760461', 1.4288563, 103.8504834, 'SG', 'North East', true),
  ('Anytime Fitness Tengah', '119 Plantation Cresent, Tengah Community Club,#02-01, Singapore 690119.', 1.3568117, 103.7346533, 'SG', 'North West', true),
  ('CSC Bukit Batok', '91, Bukit Batok West Ave 2, Block C, #05-01', 1.3527145, 103.7493724, 'SG', 'North West', true),
  ('Choa Chu Kang (Choa Chu Kang)', '190 Choa Chu Kang Avenue 1', 1.3769026, 103.7453125, 'SG', 'North West', true),
  ('Choa Chu Kang Centre', '309 Choa Chu Kang Avenue 4 #03-01', 1.3851393, 103.7457093, 'SG', 'North West', true),
  ('Hong Kah North CC', '30 Bukit Batok Street 31, #04-04 Hong Kah North Community Club', 1.3591492, 103.7493493, 'SG', 'North West', true),
  ('Lower Peirce', '16 Jalan Kuras', 1.3730818, 103.8296201, 'SG', 'North West', true),
  ('Marsiling MRT', 'BLK 303 WOODLANDS STREET 31 #01-159/161 SINGAPORE 730303', 1.4311839, 103.7740683, 'SG', 'North West', true),
  ('NTU', '110 Nanyang Cres, Singapore 636956', 1.3494, 103.6887384, 'SG', 'North West', true),
  ('Parc Point', 'Blk 302, Tengah Park Avenue, #03-02, Singapore 690302', 1.3598662, 103.738644, 'SG', 'North West', true),
  ('Sembawang', '#02-14 Sembawang Shopping Centre 604 Sembawang Road', 1.441615, 103.8246417, 'SG', 'North West', true),
  ('Sunshine Place', '475 Choa Chu Kang Avenue 3, Sunshine Place, Singapore', 1.3780266, 103.7389881, 'SG', 'North West', true),
  ('Teck Whye', 'Blk 26 Teck Whye Lane, #01-180 & #01-182', 1.3778345, 103.7558288, 'SG', 'North West', true),
  ('Wisteria', 'Wisteria Mall, B1-26/27, 598 Yishun Ring Road', 1.4181317, 103.8411962, 'SG', 'North West', true),
  ('Woodgrove', '30 Woodlands Avenue Woodgrove Drive #02-12/13 & #02-01-02/03/04 The Woodgrove, &, 739065', 1.4292977, 103.7811477, 'SG', 'North West', true),
  ('Woodlands', 'ACE The Place Community Club 120 Woodlands Avenue 1 , #02-01', 1.427508, 103.7920485, 'SG', 'North West', true),
  ('Woodlands North', 'BLK 871 WOODLANDS STREET 81 #01-292', 1.4438728, 103.7893413, 'SG', 'North West', true),
  ('Yew Tee', '20 Choa Chu Kang St 22 #03-01 Singapore', 1.3856245, 103.7464915, 'SG', 'North West', true),
  ('Yew Tee 614', 'Blk 614, Choa Chu Kang Street 62, #01-233', 1.4010767, 103.744071, 'SG', 'North West', true),
  ('537 Bedok North', 'Apt Blk 537 Bedok North Street 3, #01-555, Singapore 460537', 1.3317302, 103.9240089, 'SG', 'South East', true),
  ('Alexis', '354 Alexandra Road, Alexis, #01-01, Singapore', 1.2912179, 103.807355, 'SG', 'South East', true),
  ('Ang Mo Kio South', '340 Ang Mo Kio Ave 1,', 1.3644769, 103.8494787, 'SG', 'South East', true),
  ('Anytime Fitness Aljunied 119', 'Blk 119, #01-80/82/84, Aljunied Avenue 2, Singapore 380119', 1.3197303, 103.8865492, 'SG', 'South East', true),
  ('Bedok 85', 'BLK 88 BEDOK NORTH STREET 4 #01-163', 1.3327966, 103.9394538, 'SG', 'South East', true),
  ('Bukit Batok Connection', '2 Bukit Batok Street 23, #01-03 , Connection', 1.343902, 103.7533601, 'SG', 'South East', true),
  ('Cecil Street', '139 Cecil St, #04-01', 1.2795422, 103.8484516, 'SG', 'South East', true),
  ('Chai Chee', '750 Chai Chee Road', 1.3235573, 103.9222231, 'SG', 'South East', true),
  ('Eastpoint Mall', '3 Simei Street 6, #03-25 to 26, Eastpoint Mall', 1.3427472, 103.9530126, 'SG', 'South East', true),
  ('Geylang', '653 Geylang Rd.', 1.3144425, 103.8882642, 'SG', 'South East', true),
  ('Geylang Central', '301 Geylang Road #04-01', 1.3127734, 103.878652, 'SG', 'South East', true),
  ('Grantral Complex', '601 MacPherson Road, #02-08, Grantral Mall, Grantral Complex, 368239', 1.3335017, 103.8871113, 'SG', 'South East', true),
  ('Guillemard', '100 Guillemard Road, #01-08', 1.3097489, 103.8819562, 'SG', 'South East', true),
  ('HarbourFront', '3 HarbourFront Place, Unit #01-01', 1.2647921, 103.818827, 'SG', 'South East', true),
  ('Havelock Outram', '405 Havelock Road #02-02 Furama RiverFront,', 1.2877413, 103.8363894, 'SG', 'South East', true),
  ('Joo Chiat', '123 Joo Chiat Road, Singapore 427412', 1.3134882, 103.8996107, 'SG', 'South East', true),
  ('Kaki Bukit', '1 Kaki Bukit Rd 1, Singapore 415934', 1.3334411, 103.9027906, 'SG', 'South East', true),
  ('Katong', '174/176 East Coast Road', 1.3085237, 103.9149972, 'SG', 'South East', true),
  ('Kembangan', '18 Jalan Masjid #01-04 , #B1-06 Kembangan, Singapore 418944', 1.3203956, 103.9124968, 'SG', 'South East', true),
  ('MacPherson', 'MacPherson Community Club 400 Paya Lebar Way', 1.3236119, 103.8847295, 'SG', 'South East', true),
  ('Marine Parade', 'Blk 86 Marine Parade Central #01-670', 1.3018055, 103.906943, 'SG', 'South East', true),
  ('Mountbatten', '372 Tanjong Katong, Mountbatten', 1.3027793, 103.8968012, 'SG', 'South East', true),
  ('Paya Lebar', '#02-04, 11 Tanjong Katong Road, Kinex Mall, Singapore, South East, 437157', 1.3149231, 103.8945866, 'SG', 'South East', true),
  ('Raffles Place', '22 Malacca Street Singapore 048980', 1.2839805, 103.8507142, 'SG', 'South East', true),
  ('Sentosa', '20 Martin Road Singapore 239070', 1.291274, 103.8388803, 'SG', 'South East', true),
  ('Stevens', '383 Bukit Timah Road', 1.3195389, 103.827332, 'SG', 'South East', true),
  ('Tampines East Tampines Mart', '9 Tampines Street 32 #02-01 Tampines Mart', 1.354277, 103.9601312, 'SG', 'South East', true),
  ('Tampines Grande', '7 Tampines Grande, Singapore 528736', 1.3552599, 103.9416285, 'SG', 'South East', true),
  ('Upper Cross Street', '531 Upper Cross Street #01-07, Hong Lim Complex', 1.2844194, 103.8463085, 'SG', 'South East', true),
  ('Bedok South CC', 'Bedok community center, 850 , #02-22, New Upper Changi Road', 1.3243404, 103.9360962, 'SG', 'South West', true),
  ('Boon Lay', '221 Boon Lay Place, #03-106, Boon Lay', 1.3462025, 103.7126505, 'SG', 'South West', true),
  ('Bukit Merah', '131 Jalan Bukit Merah, #01-1589/1591, Singapore 160131', 1.280382, 103.8281128, 'SG', 'South West', true),
  ('Buona Vista', '11 Biopolis Way, #01-04/05/06/07 Helios', 1.3045201, 103.7916515, 'SG', 'South West', true),
  ('Cantonment Road', '17 Cantonment Road', 1.279172, 103.84017, 'SG', 'South West', true),
  ('City Square Mall (City Square Mall)', '180 Kitchener Road, #06-04, City Square Mall', 1.3114516, 103.8561608, 'SG', 'South West', true),
  ('Clementi City', '3151 Commonwealth Avenue, West #03-01', 1.3125415, 103.7747404, 'SG', 'South West', true),
  ('Depot Heights', '108 Depot Rd #03-02, Singapore 100108', 1.2811603, 103.8101665, 'SG', 'South West', true),
  ('Geylang Bahru', '1 Geylang Bahru Ln, #01-03 Kolam Ayer Community Club', 1.3242613, 103.8697786, 'SG', 'South West', true),
  ('Jurong', '442 Jurong West Ave 1 #01-746/ #01-748 Singapore 640442', 1.3519515, 103.7197595, 'SG', 'South West', true),
  ('Jurong East Central', '134 Jurong Gateway, #01-311', 1.3336748, 103.7387894, 'SG', 'South West', true),
  ('Jurong Point', 'Jurong Point, 1 Jurong West Central 2', 1.3399257, 103.7062886, 'SG', 'South West', true),
  ('Jurong Summit', '8 Jurong Townhall rd #02-00 JTC Summit', 1.3310786, 103.7417689, 'SG', 'South West', true),
  ('Jurong West (Nanyang)', 'Nanyang Community Club Building 60 Jurong West Street 91, #01-08', 1.3423866, 103.6922819, 'SG', 'South West', true),
  ('Labrador View', '456, Alexandra Road #12-02', 1.2752881, 103.8013377, 'SG', 'South West', true),
  ('Marymount CC', '191 Sin Ming Avenue, #03-01', 1.36229, 103.8411901, 'SG', 'South West', true),
  ('Pasir Panjang', '44 Pasir Panjang Road Blocks A & B #01', 1.2748466, 103.7941738, 'SG', 'South West', true),
  ('Pioneer Mall', '638 Jurong West Street 61 #03-1 Pioneer Mall', 1.3418206, 103.6973615, 'SG', 'South West', true),
  ('Sentosa', 'Quayside Isle, 31 Ocean Way, Sentosa Cove, Singapore 098375', 1.2476808, 103.8420723, 'SG', 'South West', true),
  ('Siglap Community Centre', '#02-11 151 Bedok South Road', 1.3180279, 103.9480475, 'SG', 'South West', true),
  ('Taman Jurong', '1 Yung Sheng Road, #01-02 Taman Jurong Community Club', 1.3352415, 103.7216118, 'SG', 'South West', true),
  ('Telok Blangah', 'Blk 78B Telok Blangah Street 32 #02-15', 1.2735728, 103.8087042, 'SG', 'South West', true),
  ('Tiong Bahru Plaza', '302 Tiong Bahru Road #01-128/129 Tiong Bahru Plaza', 1.2864763, 103.8271508, 'SG', 'South West', true),
  ('West Coast', 'West Coast Plaza 154 West Coast Road', 1.303702, 103.7659312, 'SG', 'South West', true),
  ('d''Arena Jurong', 'D’Arena, 511 Upper Jurong Road, Blk E #05', 1.329511, 103.6822241, 'SG', 'South West', true);
